### PR TITLE
Update mc_locale_de-de.json

### PR DESCRIPTION
**Pull request by Dietmar-Franken**
Changes tranlated

### CODE REVIEW

**Comment by jkandasa** [comment]
@Dietmar-Franken seems you have removed `NODE.*` and other variables, which leads to display `KEY` directly when we select your language!

**Comment by Dietmar-Franken** [comment]
@jkandasa I don´t know what happened,hoe can i fix this?

**Comment by jkandasa** [comment]
@Dietmar-Franken have a look at [mc_locale_en-us.json](https://github.com/mycontroller-org/mycontroller/blob/master/src/main/package/www/languages/mc_locale_en-us.json) and add missing variables.

**Comment by Dietmar-Franken** [comment]
ok i´ll fix this at this evening

**Comment by jkandasa** [comment]
I believe you created new pull request for this changes https://github.com/mycontroller-org/mycontroller/pull/60 hence I'm closing this pull request.

**Pull request closed without merging**
