### PR TITLE
Replace webcomponents import

### PR DESCRIPTION
**Pull request by elgarfo**
@jkandasa in reference to this thread: https://forum.mycontroller.org/topic/376/custom-widget-send-command-to-node/8

this PR resolves multiple problems which became obvious in the above mentioned thread:
- webcomponents import is not widely supported, was recently deprecated and will be removed in near future by chrome. (see: https://www.chromestatus.com/feature/5144752345317376)
- the polyfill does a good job of loading additional files but will be problematic if additional angular modules are included that way (modules will be loaded after angulars bootstrap, which causes the frontend to crash if additional modules are defined in app.js)
- there is no way to specify loading of additional modules through mycontrollers frontend

to combat a race condition between angulars bootstrap process, slower internet connections and the process of loading additional JS from local or remote servers, i opted to:
1. defer angulars bootstrapping process. (see: https://docs.angularjs.org/guide/bootstrap)
2. load additional JS resources via $.getScript (see: https://api.jquery.com/jquery.getscript/)
3. use promises to handle the asynchronous process
4. test if the specified additional angularJS modules can be loaded (angular crashes if modules can not be loaded)
5. finally resume angulars bootstrap and pass additional modules to load

this has been tested so far on windows 10 x64 1806 with firefox 63.0.3 64-bit and is working fine for me.
i've been able to plug your custom slider widget example right into the frontend without modifying app.js. as far as i can tell, the websites is working flawless, on first an subsequent visits, with or without additional modules specified.

### CODE REVIEW

**Comment by jkandasa** [comment]
@elgarfo Thank you for the awesome work!
I will review this PR soon and merge it if everything goes well.

**Comment by jkandasa** [comment]
@elgarfo All works great! Thank you so much for your contributions!
There are minor update needs,
* We should not touch locale files (ie: `mc_locale_gui-de_de.json`), We should update only `mc_locale_gui_source_en.json`, other files should be updated from https://transifex.com/mycontrollerorg/ I can push the source and make available your change in https://transifex.com/mycontrollerorg/ once I merge this PR.
* Can you add `mcv=${mc.gui.version}` for newly created files?
  * `<script src="angular_defer_bootstrap.js?mcv=${mc.gui.version}"></script>`
  * `<script src="/_configurations/additional.js?mcv=${mc.gui.version}"></script>`
  * ` <link rel="stylesheet" type="text/css" href="/_configurations/additional.css?mcv=${mc.gui.version}">`
* Update [mc.gui.version](https://github.com/mycontroller-org/mycontroller/blob/development/dist/pom.xml#L35) to `28`

**Comment by jkandasa** [comment]
@elgarfo I have updated the changes. Thanks!

**Comment by jkandasa** [comment]
@elgarfo I tested only on Chrome and I do not face any issue. It was a simple change I made.
Thank you for your great PR.

**Comment by wanvo** [comment]
I checked this widget in Chrome, it works great.
In Firefox, all menus look like this ({{variable}}.

**Comment by elgarfo** [comment]
@wanvo which version of firefox and what OS did u use? can you try with a new firefox profile?

**Comment by wanvo** [comment]
@elgarfo I am using Windows7 x64, the latest version of Firefox x64. I created a new firefox profile and I tried the widget in it.The menus look the same {{variable}}.

**Pull request merged**
