### PR TITLE
Added multilanguage

### PR DESCRIPTION
**Pull request by arturmon**

### CODE REVIEW

**Comment by jkandasa** [comment]
@arturmon thank you for your contribution!!
Right now we do not have any mechanism to test MyController on pull request. Have you tested these changes locally on your computer?

**Comment by arturmon** [comment]
I check in 12 hours. now while at work.

**Comment by jkandasa** [comment]
@arturmon thank you!

**Comment by arturmon** [comment]
maybe it's worth to take advantage of the service transifex.com,phraseapp.com or something similar?

**Comment by jkandasa** [comment]
@arturmon thank you for a great idea! let me learn more about these tools we will discuss further.

**Pull request merged**
