### PR TITLE
Updated Moquette references

### PR DESCRIPTION
**Pull request by S0rc3r3r**
Updated Moquette references as groupId has been changed to <io.moquette>
--> More info here : https://github.com/andsel/moquette

Attached local maven repository.
[io.zip](https://github.com/mycontroller-org/mycontroller/files/53566/io.zip)

### CODE REVIEW

**Comment by S0rc3r3r** [comment]
Also added the possibility to filter Sensors by nodeName by calling : 
http://xx.xx.xx.xx/mc/rest/sensors?nodeName=Living

**Comment by jkandasa** [comment]
@S0rc3r3r Thank you I merged your change. We have to follow code style. I will update detailed document for that.

**Comment by jkandasa** [comment]
@S0rc3r3r  Seems you are using tab, we have to use 4 spaces for tab and in xml 2 space

**Comment by S0rc3r3r** [comment]
Can you please export your code style profile and attache it here so that I can import into Eclipse?

~Regards

**Comment by jkandasa** [comment]
@S0rc3r3r Sure, I will create developer document with code style soon. Thank you!

**Pull request merged**
