### PR TITLE
Rename ObjectFactory -> ObjectManager

### PR DESCRIPTION
**Pull request by pgh70**
Old name hints to a factory pattern which it isn't

### CODE REVIEW

**Comment by jkandasa** [comment]
@pgh70 Thank you for your PR. can you change `ObjectFactory` -> `McObjectFactory`?
please pull recent changes from development branch and do your change

**Comment by pgh70** [comment]
Changing ObjectFactory to McObjectFactory still hints to a factory-pattern (http://www.tutorialspoint.com/design_pattern/factory_pattern.htm) which it isn't.. It is simply a class which holds references to other objects.. So a Manager is a better name for it...

**Comment by jkandasa** [comment]
@pgh70 Yes, `McObjectManager` could be a better name.

**Comment by pgh70** [comment]
Is there a reason for using this class for holding the references? For instance RawMessageQueue could be a singleton class, then there is no need to let ObjectFactory (of McObjectManager) keep track of a reference to the class... I can create a PR to demonstrate this..

**Comment by jkandasa** [comment]
@pgh70 i do not have any specific reason to hold references. I will check your changes in 3 days.  right now I'm in vacation.  sorry for the delay.  thank you.

**Comment by jkandasa** [comment]
@pgh70 can you satisfy checkstyle? 

```
[INFO] --- maven-checkstyle-plugin:2.17:checkstyle (check-style) @ mycontroller-core ---
[INFO] Starting audit...
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/db/DataBaseUtils.java:30: Wrong order for 'org.mycontroller.standalone.McObjectManager' import.
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/db/SensorUtils.java:25: Wrong order for 'org.mycontroller.standalone.McObjectManager' import.
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/gateway/serialport/SerialDataListenerjSerialComm.java:21: Wrong order for 'org.mycontroller.standalone.McObjectManager' import.
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/metrics/MetricsAggregationBase.java:360: Line is longer than 120 characters (found 121).
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/metrics/MetricsAggregationBase.java:369: Line is longer than 120 characters (found 121).
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/mqttbroker/BrokerConfiguration.java:53: Line is longer than 120 characters (found 121).
/home/travis/build/mycontroller-org/mycontroller/modules/core/src/main/java/org/mycontroller/standalone/rule/McConditionScript.java:24: Wrong order for 'org.mycontroller.standalone.McObjectManager' import.
Audit done.
```

**Comment by pgh70** [comment]
Satisfy checkstyle done (after some effort in IntelliJ) :)

**Comment by jkandasa** [comment]
@pgh70 merged your changes thank you!

**Comment by pgh70** [comment]
@jkandasa Did you also look at the conversion to singleton as shown in:
https://github.com/pgh70/mycontroller/tree/rmq-singleton
(commit: a4d2c6e516ddb8795a3f405140dc9ace267f075)

This demonstrates the conversion of RawMessageQueue to a singleton...

If you like this approach, i can make a PR with RawMessageQueue and the other classes where McObjectManager keeps a reference to, changed to singleton class which renders McObjectManager obsolete..

**Comment by jkandasa** [comment]
@pgh70 Thank you! Let me have a look and update you soon.

**Comment by jkandasa** [comment]
@pgh70 your single tone approach looks good. we can merge it. Kindly create a PR. Thank you very much for your contribution.

**Pull request merged**
