### PR TITLE
Merge pull request #3 from arturmon/patch-7

### PR DESCRIPTION
**Pull request by arturmon**
Patch 7

### CODE REVIEW

**Comment by jkandasa** [comment]
@arturmon I believe nothing to merge in this PR?

**Comment by arturmon** [comment]
update locale ru

**Comment by jkandasa** [comment]
This patch is conflicts with my change (file name changes), I hope you can update your changes easily in https://www.transifex.com/mycontrollerorg/gui-angularjs/mc_locale_gui/ ?

**Comment by jkandasa** [comment]
As we are managing locale with https://www.transifex.com no more manual change is required in locale*.json file

**Pull request closed without merging**
